version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  frontend:
    # À configurer pour Next.js
    # build: ./frontend
    # ports:
    #   - "3000:3000"
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://backend:5000/api
    # depends_on:
    #   - backend
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["tail", "-f", "/dev/null"]  # Placeholder until Next.js is set up

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
