version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    # Remplace command par entrypoint ou garde command si tu veux lancer 2 trucs (npm + flask)
    # entrypoint: ["/entrypoint.sh"]
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
